# Copyright (c) 2018-2025 Ben Fisher

from enum import StrEnum

class DXColor(StrEnum):
    """Enum of color scheme traditionally used in the VBA version of Dr Checks review.

    In order to work with Openpyxl Color classes, the color hex code '#' is removed.
    If the # is removed from the string, rather than through Replace(), IDE color hints
    no longer work.
    """
    WHITE = '#ffffff'.replace('#','')
    BLACK = '#000000'.replace('#','')

    RED = '#FF4500'.replace('#','')
    YELLOW = '#FFD700'.replace('#','')
    GREEN = '#3CB371'.replace('#','')
    BLUE = '#1E90FF'.replace('#','')
    GRAY = '#A9A9A9'.replace('#','')

    RED_TEXT = '#FF6347'.replace('#','')
    YELLOW_TEXT = '#B8860B'.replace('#','')
    GREEN_TEXT = '#548235'.replace('#','')
    BLUE_TEXT = '#0070C0'.replace('#','')
    LIGHT_GRAY_TEXT = '#C0C0C0'.replace('#','')

    LIGHT_RED_BG = '#FFE4E1'.replace('#','')
    LIGHT_YELLOW_BG = '#FFFACD'.replace('#','')
    LIGHT_GREEN_BG = '#E2EFDA'.replace('#','')
    LIGHT_BLUE_BG = '#DDEBF7'.replace('#','')
    LIGHT_GRAY_BG = '#F5F5F5'.replace('#','')

class WebColor(StrEnum): 
    """Enum of the 140 named 'webcolors' colors

    In order to work with Openpyxl Color classes, the color hex code '#' is removed.
    If the # is removed from the string, rather than through Replace(), IDE color hints
    no longer work.
    """
    MEDIUMVIOLETRED = '#c71585'.replace('#','')
    DEEPPINK = '#ff1493'.replace('#','')
    PALEVIOLETRED = '#db7093'.replace('#','')
    HOTPINK = '#ff69b4'.replace('#','')
    LIGHTPINK = '#ffb6c1'.replace('#','')
    PINK = '#ffc0cb'.replace('#','')

    DARKRED = '#8b0000'.replace('#','')
    RED = '#ff0000'.replace('#','')
    FIREBRICK = '#b22222'.replace('#','')
    CRIMSON = '#dc143c'.replace('#','')
    INDIANRED = '#cd5c5c'.replace('#','')
    LIGHTCORAL = '#f08080'.replace('#','')
    SALMON = '#fa8072'.replace('#','')
    DARKSALMON = '#e9967a'.replace('#','')
    LIGHTSALMON = '#ffa07a'.replace('#','')

    ORANGERED = '#ff4500'.replace('#','')
    TOMATO = '#ff6347'.replace('#','')
    DARKORANGE = '#ff8c00'.replace('#','')
    CORAL = '#ff7f50'.replace('#','')
    ORANGE = '#ffa500'.replace('#','')

    DARKKHAKI = '#bdb76b'.replace('#','')
    GOLD = '#ffd700'.replace('#','')
    KHAKI = '#f0e68c'.replace('#','')
    PEACHPUFF = '#ffdab9'.replace('#','')
    YELLOW = '#ffff00'.replace('#','')
    PALEGOLDENROD = '#eee8aa'.replace('#','')
    MOCCASIN = '#ffe4b5'.replace('#','')
    PAPAYAWHIP = '#ffefd5'.replace('#','')
    LIGHTGOLDENRODYELLOW = '#fafad2'.replace('#','')
    LEMONCHIFFON = '#fffacd'.replace('#','')
    LIGHTYELLOW = '#ffffe0'.replace('#','')

    MAROON = '#800000'.replace('#','')
    BROWN = '#a52a2a'.replace('#','')
    SADDLEBROWN = '#8b4513'.replace('#','')
    SIENNA = '#a0522d'.replace('#','')
    CHOCOLATE = '#d2691e'.replace('#','')
    DARKGOLDENROD = '#b8860b'.replace('#','')
    PERU = '#cd853f'.replace('#','')
    ROSYBROWN = '#bc8f8f'.replace('#','')
    GOLDENROD = '#daa520'.replace('#','')
    SANDYBROWN = '#f4a460'.replace('#','')
    TAN = '#d2b48c'.replace('#','')
    BURLYWOOD = '#deb887'.replace('#','')
    WHEAT = '#f5deb3'.replace('#','')
    NAVAJOWHITE = '#ffdead'.replace('#','')
    BISQUE = '#ffe4c4'.replace('#','')
    BLANCHEDALMOND = '#ffebcd'.replace('#','')
    CORNSILK = '#fff8dc'.replace('#','')

    INDIGO = '#4b0082'.replace('#','')
    PURPLE = '#800080'.replace('#','')
    DARKMAGENTA = '#8b008b'.replace('#','')
    DARKVIOLET = '#9400d3'.replace('#','')
    DARKSLATEBLUE = '#483d8b'.replace('#','')
    BLUEVIOLET = '#8a2be2'.replace('#','')
    DARKORCHID = '#9932cc'.replace('#','')
    FUCHSIA = '#ff00ff'.replace('#','')
    SLATEBLUE = '#6a5acd'.replace('#','')
    MEDIUMSLATEBLUE = '#7b68ee'.replace('#','')
    MEDIUMORCHID = '#ba55d3'.replace('#','')
    MEDIUMPURPLE = '#9370db'.replace('#','')
    ORCHID = '#da70d6'.replace('#','')
    VIOLET = '#ee82ee'.replace('#','')
    PLUM = '#dda0dd'.replace('#','')
    THISTLE = '#d8bfd8'.replace('#','')
    LAVENDER = '#e6e6fa'.replace('#','')

    MIDNIGHTBLUE = '#191970'.replace('#','')
    NAVY = '#000080'.replace('#','')
    DARKBLUE = '#00008b'.replace('#','')
    MEDIUMBLUE = '#0000cd'.replace('#','')
    BLUE = '#0000ff'.replace('#','')
    ROYALBLUE = '#4169e1'.replace('#','')
    STEELBLUE = '#4682b4'.replace('#','')
    DODGERBLUE = '#1e90ff'.replace('#','')
    DEEPSKYBLUE = '#00bfff'.replace('#','')
    CORNFLOWERBLUE = '#6495ed'.replace('#','')
    SKYBLUE = '#87ceeb'.replace('#','')
    LIGHTSKYBLUE = '#87cefa'.replace('#','')
    LIGHTSTEELBLUE = '#b0c4de'.replace('#','')
    LIGHTBLUE = '#add8e6'.replace('#','')
    POWDERBLUE = '#b0e0e6'.replace('#','')

    TEAL = '#008080'.replace('#','')
    DARKCYAN = '#008b8b'.replace('#','')
    LIGHTSEAGREEN = '#20b2aa'.replace('#','')
    CADETBLUE = '#5f9ea0'.replace('#','')
    DARKTURQUOISE = '#00ced1'.replace('#','')
    MEDIUMTURQUOISE = '#48d1cc'.replace('#','')
    TURQUOISE = '#40e0d0'.replace('#','')
    AQUA = '#00ffff'.replace('#','')
    AQUAMARINE = '#7fffd4'.replace('#','')
    PALETURQUOISE = '#afeeee'.replace('#','')
    LIGHTCYAN = '#e0ffff'.replace('#','')

    DARKGREEN = '#006400'.replace('#','')
    GREEN = '#008000'.replace('#','')
    DARKOLIVEGREEN = '#556b2f'.replace('#','')
    FORESTGREEN = '#228b22'.replace('#','')
    SEAGREEN = '#2e8b57'.replace('#','')
    OLIVE = '#808000'.replace('#','')
    OLIVEDRAB = '#6b8e23'.replace('#','')
    MEDIUMSEAGREEN = '#3cb371'.replace('#','')
    LIMEGREEN = '#32cd32'.replace('#','')
    LIME = '#00ff00'.replace('#','')
    SPRINGGREEN = '#00ff7f'.replace('#','')
    MEDIUMSPRINGGREEN = '#00fa9a'.replace('#','')
    DARKSEAGREEN = '#8fbc8f'.replace('#','')
    MEDIUMAQUAMARINE = '#66cdaa'.replace('#','')
    YELLOWGREEN = '#9acd32'.replace('#','')
    LAWNGREEN = '#7cfc00'.replace('#','')
    CHARTREUSE = '#7fff00'.replace('#','')
    LIGHTGREEN = '#90ee90'.replace('#','')
    GREENYELLOW = '#adff2f'.replace('#','')
    PALEGREEN = '#98fb98'.replace('#','')

    MISTYROSE = '#ffe4e1'.replace('#','')
    ANTIQUEWHITE = '#faebd7'.replace('#','')
    LINEN = '#faf0e6'.replace('#','')
    BEIGE = '#f5f5dc'.replace('#','')
    WHITESMOKE = '#f5f5f5'.replace('#','')
    LAVENDERBLUSH = '#fff0f5'.replace('#','')
    OLDLACE = '#fdf5e6'.replace('#','')
    ALICEBLUE = '#f0f8ff'.replace('#','')
    SEASHELL = '#fff5ee'.replace('#','')
    GHOSTWHITE = '#f8f8ff'.replace('#','')
    HONEYDEW = '#f0fff0'.replace('#','')
    FLORALWHITE = '#fffaf0'.replace('#','')
    AZURE = '#f0ffff'.replace('#','')
    MINTCREAM = '#f5fffa'.replace('#','')
    SNOW = '#fffafa'.replace('#','')
    IVORY = '#fffff0'.replace('#','')
    WHITE = '#ffffff'.replace('#','')

    BLACK = '#000000'.replace('#','')
    DARKSLATEGRAY = '#2f4f4f'.replace('#','')
    DIMGRAY = '#696969'.replace('#','')
    SLATEGRAY = '#708090'.replace('#','')
    GRAY = '#808080'.replace('#','')
    LIGHTSLATEGRAY = '#778899'.replace('#','')
    DARKGRAY = '#a9a9a9'.replace('#','')
    SILVER = '#c0c0c0'.replace('#','')
    LIGHTGRAY = '#d3d3d3'.replace('#','')
    GAINSBORO = '#dcdcdc'.replace('#','')

